# Generated by Django 2.1.5 on 2019-02-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoriel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutoriel_titre', models.CharField(max_length=200)),
                ('tutoriel_contenu', models.TextField()),
                ('tutoriel_publier', models.DateTimeField(verbose_name='date publiée')),
            ],
        ),
    ]
